"""add worker

Revision ID: c9ae4cb75965
Revises: d1cd39c99dfb
Create Date: 2024-05-25 13:05:15.136444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ae4cb75965'
down_revision: Union[str, None] = 'd1cd39c99dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_data', sa.LargeBinary(), nullable=True),
    sa.Column('workplace_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workplace_id'], ['workplace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('workplace', sa.Column('face_detection', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workplace', 'face_detection')
    op.drop_table('worker')
    # ### end Alembic commands ###
