"""alo

Revision ID: d1cd39c99dfb
Revises: 9e422496a08b
Create Date: 2024-05-22 20:44:09.582103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1cd39c99dfb'
down_revision: Union[str, None] = '9e422496a08b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workplace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('max_people', sa.Integer(), nullable=False),
    sa.Column('current_people', sa.Integer(), nullable=True),
    sa.Column('camera_url', sa.String(), nullable=False),
    sa.Column('green_zone_coordinates', sa.JSON(), nullable=True),
    sa.Column('red_zone_coordinates', sa.JSON(), nullable=True),
    sa.Column('alert_period', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'user_workplace', 'workplace', ['workplace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_workplace', type_='foreignkey')
    op.drop_table('workplace')
    # ### end Alembic commands ###
